version: "3"

services:
  mysql:
    build: ./bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    ports:
    - "3306:3306"
    volumes:
    - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
    - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loaderdb
      MYSQL_USER: loader
      MYSQL_PASSWORD: loader
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'png-phpmyadmin'
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - '8080:80'
    volumes:
    - /sessions